Category.create(name: "community")
Category.create(name: "personals")
Category.create(name: "events")
Category.create(name: "housing")
Category.create(name: "sale")
Category.create(name: "services")
Category.create(name: "jobs")
Category.create(name: "gigs")

Subcategory.create(category_id: 1, name: "activities")
Subcategory.create(category_id: 1, name: "artists")
Subcategory.create(category_id: 1, name: "childcare")
Subcategory.create(category_id: 1, name: "general")
Subcategory.create(category_id: 1, name: "groups")
Subcategory.create(category_id: 1, name: "pets")
Subcategory.create(category_id: 1, name: "events")
Subcategory.create(category_id: 1, name: "lost+found")
Subcategory.create(category_id: 1, name: "musicians")
Subcategory.create(category_id: 1, name: "local news")
Subcategory.create(category_id: 1, name: "politics")
Subcategory.create(category_id: 1, name: "rideshare")
Subcategory.create(category_id: 1, name: "volunteers")
Subcategory.create(category_id: 1, name: "classes")


Subcategory.create(category_id: 2, name: "strictly platonic")
Subcategory.create(category_id: 2, name: "women seek women")
Subcategory.create(category_id: 2, name: "women seeking men")
Subcategory.create(category_id: 2, name: "men seeking women")
Subcategory.create(category_id: 2, name: "men seeking men")
Subcategory.create(category_id: 2, name: "misc romance")
Subcategory.create(category_id: 2, name: "casual encounters")
Subcategory.create(category_id: 2, name: "missed connections")
Subcategory.create(category_id: 2, name: "rants and raves")


Subcategory.create(category_id: 4, name: "apts / housing")
Subcategory.create(category_id: 4, name: "rooms / shared")
Subcategory.create(category_id: 4, name: "sublets / temporary")
Subcategory.create(category_id: 4, name: "housing wanted")
Subcategory.create(category_id: 4, name: "housing swap")
Subcategory.create(category_id: 4, name: "vacation rentals")
Subcategory.create(category_id: 4, name: "parking / storage")
Subcategory.create(category_id: 4, name: "office / commercial")
Subcategory.create(category_id: 4, name: "real estate for sale")


Subcategory.create(category_id: 5, name: "antiques")
Subcategory.create(category_id: 5, name: "baby+kid")
Subcategory.create(category_id: 5, name: "barter")
Subcategory.create(category_id: 5, name: "bikes")
Subcategory.create(category_id: 5, name: "boats")
Subcategory.create(category_id: 5, name: "books")
Subcategory.create(category_id: 5, name: "business")
Subcategory.create(category_id: 5, name: "computer")
Subcategory.create(category_id: 5, name: "free")
Subcategory.create(category_id: 5, name: "furniture")
Subcategory.create(category_id: 5, name: "general")
Subcategory.create(category_id: 5, name: "household")
Subcategory.create(category_id: 5, name: "jewelry")
Subcategory.create(category_id: 5, name: "materials")
Subcategory.create(category_id: 5, name: "rvs+camp")
Subcategory.create(category_id: 5, name: "sporting")
Subcategory.create(category_id: 5, name: "tickets")
Subcategory.create(category_id: 5, name: "tools")
Subcategory.create(category_id: 5, name: "wanted")
Subcategory.create(category_id: 5, name: "appliances")
Subcategory.create(category_id: 5, name: "arts+crafts")
Subcategory.create(category_id: 5, name: "atv/utv/sno")
Subcategory.create(category_id: 5, name: "auto parts")
Subcategory.create(category_id: 5, name: "beauty+hlth")
Subcategory.create(category_id: 5, name: "cars+trucks")
Subcategory.create(category_id: 5, name: "cds/dvd/vhs")
Subcategory.create(category_id: 5, name: "cell phones")
Subcategory.create(category_id: 5, name: "clothes+acc")
Subcategory.create(category_id: 5, name: "collectibles")
Subcategory.create(category_id: 5, name: "electronics")
Subcategory.create(category_id: 5, name: "farm+garden")
Subcategory.create(category_id: 5, name: "garage sale")
Subcategory.create(category_id: 5, name: "heavy equip")
Subcategory.create(category_id: 5, name: "motorcycles")
Subcategory.create(category_id: 5, name: "music instr")
Subcategory.create(category_id: 5, name: "photo+video")
Subcategory.create(category_id: 5, name: "toys+games")
Subcategory.create(category_id: 5, name: "video gaming")


Subcategory.create(category_id: 6, name: "beauty")
Subcategory.create(category_id: 6, name: "creative")
Subcategory.create(category_id: 6, name: "computer")
Subcategory.create(category_id: 6, name: "cycle")
Subcategory.create(category_id: 6, name: "event")
Subcategory.create(category_id: 6, name: "financial")
Subcategory.create(category_id: 6, name: "legal")
Subcategory.create(category_id: 6, name: "lessons")
Subcategory.create(category_id: 6, name: "marine")
Subcategory.create(category_id: 6, name: "pet")
Subcategory.create(category_id: 6, name: "automotive")
Subcategory.create(category_id: 6, name: "farm+garden")
Subcategory.create(category_id: 6, name: "household")
Subcategory.create(category_id: 6, name: "labor/move")
Subcategory.create(category_id: 6, name: "skill'd trade")
Subcategory.create(category_id: 6, name: "real estate")
Subcategory.create(category_id: 6, name: "sm biz ads")
Subcategory.create(category_id: 6, name: "therapeutic")
Subcategory.create(category_id: 6, name: "travel/vac")
Subcategory.create(category_id: 6, name: "write/ed/tr8")


Subcategory.create(category_id: 7, name: "accounting+finance")
Subcategory.create(category_id: 7, name: "admin / office")
Subcategory.create(category_id: 7, name: "arch / engineering")
Subcategory.create(category_id: 7, name: "art / media / design")
Subcategory.create(category_id: 7, name: "biotech / science")
Subcategory.create(category_id: 7, name: "business / mgmt")
Subcategory.create(category_id: 7, name: "customer service")
Subcategory.create(category_id: 7, name: "education")
Subcategory.create(category_id: 7, name: "food / bev / hosp")
Subcategory.create(category_id: 7, name: "general labor")
Subcategory.create(category_id: 7, name: "government")
Subcategory.create(category_id: 7, name: "human resources")
Subcategory.create(category_id: 7, name: "internet engineers")
Subcategory.create(category_id: 7, name: "legal / paralegal")
Subcategory.create(category_id: 7, name: "manufacturing")
Subcategory.create(category_id: 7, name: "marketing / pr / ad")
Subcategory.create(category_id: 7, name: "medical / health")
Subcategory.create(category_id: 7, name: "nonprofit sector")
Subcategory.create(category_id: 7, name: "real estate")
Subcategory.create(category_id: 7, name: "retail / wholesale")
Subcategory.create(category_id: 7, name: "sales / biz dev")
Subcategory.create(category_id: 7, name: "salon / spa / fitness")
Subcategory.create(category_id: 7, name: "security")
Subcategory.create(category_id: 7, name: "skilled trade / craft")
Subcategory.create(category_id: 7, name: "software / qa / dba")
Subcategory.create(category_id: 7, name: "systems / network")
Subcategory.create(category_id: 7, name: "technical support")
Subcategory.create(category_id: 7, name: "transport")
Subcategory.create(category_id: 7, name: "tv / film / video")
Subcategory.create(category_id: 7, name: "web / info design")
Subcategory.create(category_id: 7, name: "writing / editing")
Subcategory.create(category_id: 7, name: "[ETC]")
Subcategory.create(category_id: 7, name: "[ part-time ]")


Subcategory.create(category_id: 8, name: "crew")
Subcategory.create(category_id: 8, name: "event")
Subcategory.create(category_id: 8, name: "labor")
Subcategory.create(category_id: 8, name: "talent")
Subcategory.create(category_id: 8, name: "computer")
Subcategory.create(category_id: 8, name: "creative")
Subcategory.create(category_id: 8, name: "domestic")
Subcategory.create(category_id: 8, name: "writing")