User.create(email: "paris@email.com", password: "password", region: "brooklyn")

Category.create(name: "community")
Category.create(name: "personals")
Category.create(name: "events")
Category.create(name: "housing")
Category.create(name: "sale")


Subcategory.create(category_id: 1, name: "activities")
Subcategory.create(category_id: 1, name: "artists")
Subcategory.create(category_id: 1, name: "childcare")
Subcategory.create(category_id: 1, name: "general")
Subcategory.create(category_id: 1, name: "groups")
Subcategory.create(category_id: 1, name: "pets")
Subcategory.create(category_id: 1, name: "events")
Subcategory.create(category_id: 1, name: "lost+found")
Subcategory.create(category_id: 1, name: "musicians")
Subcategory.create(category_id: 1, name: "local news")
Subcategory.create(category_id: 1, name: "politics")
Subcategory.create(category_id: 1, name: "rideshare")
Subcategory.create(category_id: 1, name: "volunteers")
Subcategory.create(category_id: 1, name: "classes")


Subcategory.create(category_id: 2, name: "strictly platonic")
Subcategory.create(category_id: 2, name: "women seek women")
Subcategory.create(category_id: 2, name: "women seeking men")
Subcategory.create(category_id: 2, name: "men seeking women")
Subcategory.create(category_id: 2, name: "men seeking men")
Subcategory.create(category_id: 2, name: "misc romance")
Subcategory.create(category_id: 2, name: "casual encounters")
Subcategory.create(category_id: 2, name: "missed connections")
Subcategory.create(category_id: 2, name: "rants and raves")


Subcategory.create(category_id: 4, name: "apts / housing")
Subcategory.create(category_id: 4, name: "rooms / shared")
Subcategory.create(category_id: 4, name: "sublets / temporary")
Subcategory.create(category_id: 4, name: "housing wanted")
Subcategory.create(category_id: 4, name: "housing swap")
Subcategory.create(category_id: 4, name: "vacation rentals")
Subcategory.create(category_id: 4, name: "parking / storage")
Subcategory.create(category_id: 4, name: "office / commercial")
Subcategory.create(category_id: 4, name: "real estate for sale")


Subcategory.create(category_id: 5, name: "antiques")
Subcategory.create(category_id: 5, name: "baby+kid")
Subcategory.create(category_id: 5, name: "barter")
Subcategory.create(category_id: 5, name: "bikes")
Subcategory.create(category_id: 5, name: "boats")
Subcategory.create(category_id: 5, name: "books")
Subcategory.create(category_id: 5, name: "business")
Subcategory.create(category_id: 5, name: "computer")
Subcategory.create(category_id: 5, name: "free")
Subcategory.create(category_id: 5, name: "furniture")
Subcategory.create(category_id: 5, name: "general")
Subcategory.create(category_id: 5, name: "household")
Subcategory.create(category_id: 5, name: "jewelry")
Subcategory.create(category_id: 5, name: "materials")
Subcategory.create(category_id: 5, name: "rvs+camp")
Subcategory.create(category_id: 5, name: "sporting")
Subcategory.create(category_id: 5, name: "tickets")
Subcategory.create(category_id: 5, name: "tools")
Subcategory.create(category_id: 5, name: "wanted")
Subcategory.create(category_id: 5, name: "appliances")
Subcategory.create(category_id: 5, name: "arts+crafts")
Subcategory.create(category_id: 5, name: "atv/utv/sno")
Subcategory.create(category_id: 5, name: "auto parts")
Subcategory.create(category_id: 5, name: "beauty+hlth")
Subcategory.create(category_id: 5, name: "cars+trucks")
Subcategory.create(category_id: 5, name: "cds/dvd/vhs")
Subcategory.create(category_id: 5, name: "cell phones")
Subcategory.create(category_id: 5, name: "clothes+acc")
Subcategory.create(category_id: 5, name: "collectibles")
Subcategory.create(category_id: 5, name: "electronics")
Subcategory.create(category_id: 5, name: "farm+garden")
Subcategory.create(category_id: 5, name: "garage sale")
Subcategory.create(category_id: 5, name: "heavy equip")
Subcategory.create(category_id: 5, name: "motorcycles")
Subcategory.create(category_id: 5, name: "music instr")
Subcategory.create(category_id: 5, name: "photo+video")
Subcategory.create(category_id: 5, name: "toys+games")
Subcategory.create(category_id: 5, name: "video gaming")

HousingPostMaker.make_posts